### PR TITLE
Update to use Vaadin 8. Fix pom

### PR DESCRIPTION
**Pull request by rogozinds**
Change-Id: I5f91c1af78e2600f03f543ef7aa70f05fffd89ca

Conflicts:
	pom.xml

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet-demo/3)

### CODE REVIEW

**Comment by alvarezguille** [comment]
```
Caused by: java.lang.NullPointerException
	at org.reflections.Reflections.scan(Reflections.java:220)
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:94)
	at org.reflections.Reflections.<init>(Reflections.java:135)
	at org.reflections.Reflections.<init>(Reflections.java:108)
	at com.vaadin.addon.spreadsheet.demo.SpreadsheetDemoUI.getExamples(SpreadsheetDemoUI.java:289)
```
can't run current demo

**Comment by alvarezguille** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/addon/spreadsheet/demo/examples/ChartExample.java, line 5 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet-demo/3#-KXphlfnxHmXsbMI2jvK:-KXphlfoh7p9s4qwXp4C:boenwgr) ([raw file](https://github.com/vaadin/spreadsheet-demo/blob/b99e8b9062e683a26e95f8ba1bf4aaa856a69471/src/main/java/com/vaadin/addon/spreadsheet/demo/examples/ChartExample.java#L5)):*
> org.reflections.util.Utils.isEmpty
pretty sure this still works, not sure why change it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet-demo/3)*

**Comment by alvarezguille** [comment]
* Set main logo width to 100%
* NPE clicking C2 in inline components demo
* Different size for native select in inline components demo

---

Reviewed 1 of 1 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet-demo/3#-:-KXtHZjbJiZLmy09D4Dh:bhvett0)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 2 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 23 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet-demo/3#-KXtbEeT0zVgpq0D5s4n:-KXtbEeT0zVgpq0D5s4o:b-sxt8ne) ([raw file](https://github.com/vaadin/spreadsheet-demo/blob/98f1f52d76242f0039e3ed12d24b2ccd8d455e61/pom.xml#L23)):*
> ```XML
> 		<vaadin.plugin.version>8.0.0.alpha7</vaadin.plugin.version>
> 		<spreadsheet.version>2.0.0.alpha1</spreadsheet.version>
> 		<vaadin.charts.version>4.0.0-alpha2</vaadin.charts.version>
> ```

4.0.0-alpha2 is not compatible with framework 8.0.0.alpha7 but I guess there's no problem because the demo isn't using DataProviderSeries

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet-demo/3)*

**Comment by rogozinds** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 23 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet-demo/3#-KXtbEeT0zVgpq0D5s4n:-KXu_89N5oUe-wntGy-p:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet-demo/blob/98f1f52d76242f0039e3ed12d24b2ccd8d455e61/pom.xml#L23)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

4.0.0-alpha2 is not compatible with framework 8.0.0.alpha7 but I guess there's no problem because the demo isn't using DataProviderSeries
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/addon/spreadsheet/demo/examples/ChartExample.java, line 5 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet-demo/3#-KXphlfnxHmXsbMI2jvK:-KXuYlWd6XhazFy2fsxy:brhaaay) ([raw file](https://github.com/vaadin/spreadsheet-demo/blob/b99e8b9062e683a26e95f8ba1bf4aaa856a69471/src/main/java/com/vaadin/addon/spreadsheet/demo/examples/ChartExample.java#L5)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> org.reflections.util.Utils.isEmpty
pretty sure this still works, not sure why change it
</blockquote></details>

It's not. The implementation of the method is very straightforward:
   public static boolean isEmpty(String s) {
        return s == null || s.length() == 0;
    }

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet-demo/3)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 8 files at r1, 2 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet-demo/3)*

**Pull request merged**
